version: "3.8"

services:
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
